name: Deploy UI

on:
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 7.13.2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'pnpm'
    - name: Install
      run: pnpm install --filter=!./xmcl-page --filter=!./electron-app
    - name: Build
      run: |
        pnpm run --prefix xmcl-keystone-ui build
      env:
        BUILD_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}
    - name: Deploy to vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-args: '--prod ./xmcl-keystone-ui/dist'
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
